/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import type { IOperationResult } from '@microsoft/power-apps/data';
import type { Product } from '../models/OpenFoodFactsModel';
import { dataSourcesInfo } from '../../../.power/schemas/appschemas/dataSourcesInfo';
import { getClient } from '@microsoft/power-apps/data';


export class OpenFoodFactsService {
  private static readonly dataSourceName = 'OpenFoodFacts';

  private static readonly client = getClient(dataSourcesInfo);

  public static async GetProductByBarcode(barcode: string): Promise<IOperationResult<Product>> {
    const result = await OpenFoodFactsService.client.executeAsync<{ barcode: string }, Product>({
      connectorOperation: {
        tableName: OpenFoodFactsService.dataSourceName,
        operationName: 'GetProductByBarcode',
        parameters: { barcode },
      },
    });
    return result;
  }

  // The swagger exposes a second operation, GetProductImage, which proxies the image bytes
  // through the connector's own server-side code - the browser cannot fetch the Open Food
  // Facts image URL directly. Typed as unknown because the transport hands back a base64
  // string, an ArrayBuffer or a Uint8Array depending on the runtime; the caller normalises.
  public static async GetProductImage(imageUrl: string): Promise<IOperationResult<unknown>> {
    const result = await OpenFoodFactsService.client.executeAsync<{ imageUrl: string }, unknown>({
      connectorOperation: {
        tableName: OpenFoodFactsService.dataSourceName,
        operationName: 'GetProductImage',
        parameters: { imageUrl },
      },
    });
    return result;
  }
}
